# Generated by Django 2.1.7 on 2019-03-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_adicionaratendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionaratendimento',
            name='nomePaciente',
            field=models.CharField(max_length=300),
        ),
    ]
