# Generated by Django 2.1.7 on 2019-03-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20190326_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionaratendimento',
            name='nomePaciente',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
