# Generated by Django 2.1.7 on 2019-03-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20190326_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionaratendimento',
            name='nomePaciente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
