# Generated by Django 2.1.7 on 2019-03-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_auto_20190326_2050'),
        ('agenda', '0002_auto_20190322_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='especializacao',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='medico.especializacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='nomeMedico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
    ]
