# Generated by Django 2.1.7 on 2019-03-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20190327_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='especializacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medico.especializacao'),
        ),
    ]
