# Generated by Django 2.1.7 on 2019-03-26 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_auto_20190326_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='especializacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='especializacao',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='medico.especializacao'),
            preserve_default=False,
        ),
    ]
