# Generated by Django 2.1.7 on 2019-03-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0005_auto_20190326_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especializacao',
            name='nome',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
